export const SET_LOADING = 'SET_LOADING'

export const ACCOUNT = {
    SET_ACCOUNT: 'SET_ACCOUNT',
    SET_ACCOUNTS: 'SET_ACCOUNTS',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SET_CLEAR_ERROR_MESSAGE: 'SET_CLEAR_ERROR_MESSAGE',
}
export const ADMINUSER = {
    SET_USER: 'SET_USER',
    SET_USERS: 'SET_USERS',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SET_CLEAR_ERROR_MESSAGE: 'SET_CLEAR_ERROR_MESSAGE',
}
export const ADMINOWNER = {
    SET_OWNER: 'SET_OWNER',
    SET_OWNERS: 'SET_OWNERS',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SET_CLEAR_ERROR_MESSAGE: 'SET_CLEAR_ERROR_MESSAGE',
}
export const OWNERROOM = {
    SET_ROOMS: 'SET_ROOMS',
    SET_USERS: 'SET_USERS',
    SET_TOTALRECORD: 'SET_TOTALRECORD',
    SET_ROOMTYPES: 'SET_ROOMTYPES',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SET_CLEAR_ERROR_MESSAGE: 'SET_CLEAR_ERROR_MESSAGE',
}
export const OWNERUSER = {
    SET_USER: 'SET_USER',
    SET_USERS: 'SET_USERS',
    SET_TOTALRECORD: 'SET_TOTALRECORD',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SET_CLEAR_ERROR_MESSAGE: 'SET_CLEAR_ERROR_MESSAGE',
}
export const OWNERBILL = {
    SET_BILLS: 'SET_BILLS',
    SET_BILL: 'SET_BILL',
    SET_TOTALRECORD: 'SET_TOTALRECORD',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SET_CLEAR_ERROR_MESSAGE: 'SET_CLEAR_ERROR_MESSAGE',
}
export const OWNERHOSTEL = {
    SET_HOSTELS: 'SET_HOSTELS',
    SET_HOSTEL: 'SET_HOSTEL',
    SET_TOTALRECORD: 'SET_TOTALRECORD',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SET_CLEAR_ERROR_MESSAGE: 'SET_CLEAR_ERROR_MESSAGE',
}
export const OWNERBOOKING = {
    SET_BOOKINGS: 'SET_BOOKINGS',
    SET_BOOKING: 'SET_BOOKING',
    SET_TOTALRECORD: 'SET_TOTALRECORD',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SET_CLEAR_ERROR_MESSAGE: 'SET_CLEAR_ERROR_MESSAGE',
}
export const LOGIN = {
    SET_LOGIN: 'SET_LOGIN',
    SET_LOGOUT: 'SET_LOGOUT',
    SET_REGISTER: 'SET_REGISTER',
    SET_ACCOUNT: 'SET_ACCOUNT',
}
