export const SET_LOADING = 'SET_LOADING'

export const ACCOUNT = {
    SET_ACCOUNT: 'SET_ACCOUNT',
    SET_ACCOUNTS: 'SET_ACCOUNTS',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SET_CLEAR_ERROR_MESSAGE: 'SET_CLEAR_ERROR_MESSAGE',
}
export const ADMINUSER = {
    SET_USER: 'SET_USER',
    SET_USERS: 'SET_USERS',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SET_CLEAR_ERROR_MESSAGE: 'SET_CLEAR_ERROR_MESSAGE',
}
export const ADMINOWNER = {
    SET_OWNER: 'SET_OWNER',
    SET_OWNERS: 'SET_OWNERS',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SET_CLEAR_ERROR_MESSAGE: 'SET_CLEAR_ERROR_MESSAGE',
}
export const LOGIN = {
    SET_LOGIN: 'SET_LOGIN',
    SET_LOGOUT: 'SET_LOGOUT',
    SET_REGISTER: 'SET_REGISTER',
    SET_ACCOUNT: 'SET_ACCOUNT',
}
